global:
  scrape_interval: 15s


scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: mongodb-local
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: nginx
    static_configs:
      - targets: ['nginx-exporter:9113']
      
  - job_name: kafka
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: api
    dns_sd_configs:
      - names: ['api'] 
        type: 'A'
        port: 5005

  - job_name: email-service
    static_configs:
      - targets: ['notifications:8888']
  