{
 "title": "API Dashboard",
 "description": "Dashboard for displaying metrics relating to my Video Game Exchange API",
 "tags": [
  "app-metrics",
  "performance",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Avg HTTP Response Time (sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_request_duration_seconds_sum[5m]))/sum by (method) (rate(http_request_duration_seconds_count[5m]))*1000",
     "legendFormat": "{{method}} - Response Time"
    }
   ]
  },
  {
   "title": "HTTP Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_request_duration_seconds_count[1m])*60)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "CPU Usage (Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "CPU Usage" }
   ]
  },
  {
   "title": "Memory Usage (Resident)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Resident Memory" }
   ]
  },
  {
   "title": "Active Resources",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_active_resources_total", "legendFormat": "Active Resources" }
   ]
  }
 ]
}