events { }

http {
    server {
        listen 80;
        location / {
            # Utilizes nginx's built in default round robin for replicas of a named service
            proxy_pass http://api:5005;
        }
    }
    server {
        listen 8080;
        location = /basic_status {
            stub_status;

            allow 127.0.0.1;
            allow 172.16.0.0/12;
            deny all;
        }
    }
}

